databaseChangeLog:
  - changeSet:
      id: CT-SchemaDetails
      author: ajithkumar.s
      changes:
        - createTable:
            tableName: SchemaDetails
            columns:
              - column:
                  name: name
                  type: varchar(100)
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: tenantId
                  type: bigint
                  constraints:
                    unique: true

  - changeSet:
      id: CT-TenantDetails
      author: ajithkumar.s
      changes:
        - createTable:
            tableName: TenantDetails
            columns:
              - column:
                  name: tenantId
                  type: bigint
                  constraints:
                    nullable: false
                    references: SchemaDetails(tenantId)
                    foreignKeyName: TenantDetails_tenantId_SchemaDetails
                    deleteCascade: true
              - column:
                  name: storageSize
                  type: bigint
                  constraints:
                    nullable: false

  - changeSet:
      id: CT-SchemaDetailsLock
      author: ajithkumar.s
      changes:
        - createTable:
            tableName: SchemaDetailsLock
            columns:
              - column:
                  name: lockName
                  type: varchar(100)
                  constraints:
                    primaryKey: true
                    nullable: false